### ISSUE TITLE
Add `go mod tidy` to install script

### ISSUE THREAD

**Issue by breakfast0x** [0glabs/0g-chain#17]
It might be worthwhile adding `go mod tidy` to the install script [here](https://github.com/0glabs/0g-chain/blob/v0.1.0/networks/testnet/install.sh#L16) since it kept failing for me and the error message was rather cryptic.

What fixed it for me was running `go mod tidy`.

Might have been because I installed go via `apt-get` before running the script, not realizing that it automatically installs go via `snap`.

**Comment by ethanz0g** [comment]
Hello @breakfast0x ,

I just tried ``` go mod tidy ``` and the content of file ```go.mod```  and ```go.sum``` didn't change. So basically that meant the modules had been tidy already.

Meanwhile this script [install.sh](https://github.com/0glabs/0g-chain/blob/v0.1.0/networks/testnet/install.sh#L16) installs ```go``` only if it's not been included in your PATH, which usually means it's not installed yet.

**Comment by ethanz0g** [comment]
Can't repro.
