### ISSUE TITLE
Service Stop and Already Stopped Error

### ISSUE THREAD

**Issue by z8000kr** [0glabs/0g-chain#22]
The log entries related to service stop and the "already stopped" error indicate that the WebSocket server attempted to stop a connection but encountered an issue. The "already stopped" error suggests that the connection was already closed or terminated

–--–--------------–--–--------------
8:04PM ERR Failed to read request err="websocket: close 1006 (abnormal closure): unexpected EOF" module=rpc-server protocol=websocket remote={"IP":"
127.0.0.1"
,"Port":45592,"Zone":""} server=node
8:04PM INF service stop impl={"Logger":{}} module=rpc-server msg={} protocol=websocket remote={"IP":"127.0.0.1","Port":45592,"Zone":""} server=node
8:04PM ERR error while stopping connection error="already stopped" module=rpc-server protocol=websocket server=node
8:04PM INF Timed out dur=4671.539406 height=408985 module=consensus round=0 server=node step=1

**Comment by ethanz0g** [comment]
Hello @z8000kr ,

The above error messages were generated from JSON-RPC Service of cometBFT (Tendermint Core). It may or may not be an issue for 0g-chain. We may need to find a way to reproduce these error messages steadily in order to further investigate the issue.

**Comment by ethanz0g** [comment]
Can't repro
